### ISSUE TITLE
Enable Disqus

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#15]
Disqus is currently not enabled on meeting pages. It needs to be.

**Comment by jmreynolds** [comment]
Ugh. I played around with this some. It seems the injector from Discus is choking on something. Not sure what.

**Comment by jonthenerd** [comment]
I've got it working on my blog (which is also Jekyll-based), so I'll look at it shortly. It could also be related to the canonical URL being incorrect in the meta tags...

**Comment by jmreynolds** [comment]
Could be. I probably need to add you to something on Discus. Or just delete the whole thing and start over – I think I accidently created it in my own Org instead of in NHDNUG…

Blech.

Joseph Reynolds
http://www.infocraft.net
Microsoft C# MVP
Notice: This e-mail message is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. If you are the intended recipient but do not wish to receive communications through this medium, please so advise the sender immediately.

**Comment by jonthenerd** [comment]
Keep in mind there's no way to test it locally unless you modify your hosts file (so no testing from localhost).

**Comment by jonthenerd** [comment]
Please merge #17.

**Comment by jmreynolds** [comment]
Merged.
